name: Build and Release

permissions:
  contents: write

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 22 * * 2'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          repository: 'ranzonsan/CreateBangumiDatabase'
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.204'
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build project
        run: dotnet build --configuration Release
      
      - name: Run compiled executable
        run: |
          chmod +x ./CreateBangumiDatabase/bin/Release/net8.0/CreateBangumiDatabase
          ./CreateBangumiDatabase/bin/Release/net8.0/CreateBangumiDatabase
          
      - name: Archive output
        run: |
          mkdir Release
          zip -r Release/BangumiArchive.zip /home/runner/work/CreateBangumiDatabase/CreateBangumiDatabase/BangumiArchive.db
          
      - name: Fetch JSON and extract release name
        id: fetch_json
        run: |
          curl -sSL https://raw.githubusercontent.com/bangumi/Archive/refs/heads/master/aux/latest.json -o latest.json
          RELEASE_NAME=$(jq -r '.updated_at' latest.json)
          echo "RELEASE_NAME=${RELEASE_NAME}" >> $GITHUB_ENV
          
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false
          files: ./Release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
